name: Reviewdog

on:
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  gofmt:
    name: Go Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: find . -not -path '*/\.git/*' -type f -name '*.go' -exec gofmt -s -w {} \+
      - uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e

  whitespace:
    name: Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: find . -not -path '*/\.git/*' -type f -not -name '*.go' -exec sed -i 's/[[:space:]]\{1,\}$//' {} \+
      - uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e
